In [1]:
import numpy as np

In [2]:
np.array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

In [7]:
b = np.array("dataedu")
type(b)

numpy.ndarray

In [8]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [10]:
np.arange(1, 6, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [11]:
range(1, 6, 0.5)

TypeError: 'float' object cannot be interpreted as an integer

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.array([[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]])

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [15]:
np.array([[1,2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.ones((2, 5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
np.zeros((2, 5), dtype="int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [19]:
np.full((2, 5), 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [20]:
np.full((3, 3), 12
        )

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [21]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.array([
  [[1, 2, 3, 4], [5, 6, 7, 8]], 
  [[1, 2, 3, 4], [5, 6, 7, 8]], 
  [[1, 2, 3, 4], [5, 6, 7, 8]], 
])

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [24]:
arr_1d = np.array([1,2, 3, 4])


In [26]:
arr_1d.shape

(4,)

In [27]:
arr_1d.size

4

In [28]:
arr_1d.ndim

1