In [4]:
from sklearn.datasets import load_breast_cancer 
breast_cancer = load_breast_cancer() 
data = breast_cancer.data
target = breast_cancer.target 

# print(data)
# print(target)

from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(
  data, 
  target, 
  test_size = 0.3, 
  random_state=2022
  )

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(398, 30) (171, 30) (398,) (171,)


In [6]:
X_train, X_test, y_train, y_test = train_test_split(
  data, 
  target, 
  test_size = 0.3, 
  random_state=2022,
  stratify=target
  )
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(398, 30) (171, 30) (398,) (171,)


## K-fold 
* 가장 보편적으로 사용되는 교차 검증 기법
* 먼저 K개의 데이터 폴드 세트를 만들어서 K번만큼 각 폴드 세트에 학습고 검증 평가를 1반복적으로 수행하는 방법
* 학습 데이터 세트와 검증 데이터 세트를 점진적으로 변경하면서 마지막 5번째(K번째)까지 학습과 검증을 수행하는 것이 바로 K 폴드 교차 검증

In [20]:
import numpy as np 
X = np.arange(20) 

from sklearn.model_selection import KFold 
kFold = KFold(n_splits=5)

for train_idx, test_idx in kFold.split(X): 
  print(f'학습 : {train_idx}, 평가 : {test_idx}')

학습 : [ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19], 평가 : [0 1 2 3]
학습 : [ 0  1  2  3  8  9 10 11 12 13 14 15 16 17 18 19], 평가 : [4 5 6 7]
학습 : [ 0  1  2  3  4  5  6  7 12 13 14 15 16 17 18 19], 평가 : [ 8  9 10 11]
학습 : [ 0  1  2  3  4  5  6  7  8  9 10 11 16 17 18 19], 평가 : [12 13 14 15]
학습 : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15], 평가 : [16 17 18 19]


In [21]:
import numpy as np 
X = np.arange(15)
y = [0] * 6 + [1] * 3 + [2] * 6 

from sklearn.model_selection import StratifiedKFold
kFold = StratifiedKFold(n_splits=3)

for train_idx, test_idx in kFold.split(X, y): 
  print(f"학습: {train_idx}, 평가: {test_idx}")

학습: [ 2  3  4  5  7  8 11 12 13 14], 평가: [ 0  1  6  9 10]
학습: [ 0  1  4  5  6  8  9 10 13 14], 평가: [ 2  3  7 11 12]
학습: [ 0  1  2  3  6  7  9 10 11 12], 평가: [ 4  5  8 13 14]


In [2]:
from sklearn.datasets import load_breast_cancer 
breast_cancer = load_breast_cancer() 
data = breast_cancer.data 
target = breast_cancer.target 

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.3, random_state=2022)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(398, 30)
(171, 30)
(398,)
(171,)


In [6]:
# K-fold 
import numpy as np 
X = np.arange(10)

from sklearn.model_selection import KFold 
kfold = KFold(n_splits=5)

for train_idx, test_idx in kfold.split(X):
  print(train_idx, test_idx)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [9]:
import numpy as np 
X = np.arange(15)
y = [0] * 6 + [1] * 3 + [2] * 6 

from sklearn.model_selection import StratifiedKFold 
kfold = StratifiedKFold(n_splits=3)

for train_idx, test_idx in kfold.split(X, y): 
  print(train_idx, test_idx)

[ 2  3  4  5  7  8 11 12 13 14] [ 0  1  6  9 10]
[ 0  1  4  5  6  8  9 10 13 14] [ 2  3  7 11 12]
[ 0  1  2  3  6  7  9 10 11 12] [ 4  5  8 13 14]


In [2]:
from sklearn.datasets import load_breast_cancer 
breast_cancer = load_breast_cancer()
data = breast_cancer.data 
target = breast_cancer.target 

from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.3, random_state=2022)

In [4]:
X_train.shape

(398, 30)

In [5]:
import numpy as np 

X = np.arange(10) 

from sklearn.model_selection import KFold 
kfold = KFold(n_splits=5)

for train_idx, test_idx in kfold.split(X):
  print(train_idx, test_idx)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [10]:
from sklearn.datasets import load_breast_cancer 
breast_cancer =load_breast_cancer()
data = breast_cancer.data 
target = breast_cancer.target 

from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(
  data, 
  target, 
  test_size=0.3, 
  random_state=2022
)




(398,)

In [12]:
import numpy as np 
X = np.arange(10) 

from sklearn.model_selection import KFold 
kfold = KFold(n_splits=5)

kfold

for train_idx, test_idx, in kfold.split(X): 
  print(train_idx, test_idx)

KFold(n_splits=5, random_state=None, shuffle=False)

In [31]:
import numpy as np 
X = np.arange(15) 
y = [0] * 6 + [1] * 3 + [2] * 6 

from sklearn.model_selection import StratifiedKFold
kFolds = StratifiedKFold(n_splits=3)


for train_idx, test_idx in kFolds.split(X, y): 
  print(train_idx, test_idx)

[ 2  3  4  5  7  8 11 12 13 14] [ 0  1  6  9 10]
[ 0  1  4  5  6  8  9 10 13 14] [ 2  3  7 11 12]
[ 0  1  2  3  6  7  9 10 11 12] [ 4  5  8 13 14]
