In [ ]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [ ]:
obj = { "Class": ["A", "B", "A", "C", "E", "D", "D", "A", "F"]}
df = pd.DataFrame(obj)

In [ ]:
df

In [ ]:
encoder = LabelEncoder() 
encoder.fit(df["Class"])
labels = encoder.transform(df.Class)

In [ ]:
print(labels)

In [ ]:
encoder.classes_

In [ ]:
print(encoder.inverse_transform(labels))

In [ ]:
import numpy as np

In [ ]:
conditionList = [
  (df["Class"] == "A"),
  (df["Class"] == "B"),
  (df["Class"] == "C"),
  (df["Class"] == "D"),
  (df["Class"] == "E"),
  (df["Class"] == "F"),
]

choiceList = list(range(6))

np.select(condlist=conditionList, choicelist=choiceList)

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder 

obj = { "Class": ["A", "B", "A", "C", "E", "D", "D", "A", "F"]}
df = pd.DataFrame(obj)

In [ ]:
encoder = LabelEncoder() 
encoder.fit(df["Class"])

In [ ]:
labels = encoder.transform(df["Class"]).reshape(-1, 1)

In [ ]:
labels

In [ ]:
oh_encoder = OneHotEncoder(sparse_output=False)
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

In [ ]:
oh_labels

In [ ]:
df

In [ ]:
obj = { "Class": ["A", "B", "A", "C", "E", "D", "D", "A", "F"]}
df = pd.DataFrame(obj) 
pd.get_dummies(df)

In [ ]:
pd.get_dummies(df, drop_first=True)

In [ ]:
df["Class_B"] = np.where(df["Class"] == "B", 1, 0)
df["Class_C"] = np.where(df["Class"] == "C", 1, 0)
df["Class_D"] = np.where(df["Class"] == "D", 1, 0)
df["Class_E"] = np.where(df["Class"] == "E", 1, 0)
df["Class_F"] = np.where(df["Class"] == "F", 1, 0)

In [ ]:
df

In [ ]:
df.loc[df["Class"] == "B", "Class_B"] = 1

In [ ]:
df

In [ ]:
obj = { "Class": ["A", "B", "A", "C", "E", "D", "D", "A", "F"]}
df = pd.DataFrame(obj)

In [ ]:
df

In [ ]:
df.loc[df["Class"] == "B", "Class_B"] = 1
df.loc[df["Class"] != "B", "Class_B"] = 0

In [ ]:
df

In [ ]:
import pandas as pd
import numpy as np 
from sklearn.preprocessing import LabelEncoder, OneHotEncoder 

obj = {
  "student_id": ["s1", "s2", "s3", "s4", "s5", "s6"], 
  "score": [55, 90, 85, 71, 63, 99]
}
df = pd.DataFrame(obj)
df

In [ ]:
df['grade'] = pd.cut(df["score"], bins=[0, 60, 70, 89, 90, 100], labels=["가", "양", "미", "우", "수"])

In [ ]:
df

In [ ]:
lb_encoder = LabelEncoder() 
lb_encoder.fit(df["grade"])
lb_labels = lb_encoder.transform(df["grade"])
print(lb_labels)

In [ ]:
lb_labels_2d = lb_labels.reshape(-1, 1)

In [ ]:
oh_encoder = OneHotEncoder(sparse_output=False)
# oh_encoder.fit("lb_labels_2d")

In [ ]:
oh_encoder.fit(lb_labels_2d)

In [ ]:
oh_labels = oh_encoder.transform(lb_labels_2d)
oh_labels

In [ ]:
from sklearn.preprocessing import LabelEncoder 

obj = {"Class": ["A", "B", "A", "C", "E", "D", "D", "A", "F"]}
df = pd.DataFrame(obj)

In [ ]:
encoder = LabelEncoder()
encoder.fit(df["Class"])
labels = encoder.transform(df.Class)

In [ ]:
labels

In [ ]:
data = {"Color": ["Red", "Blue", "Green", "Blue", "Red", "Yellow", "Green", "Red", "Blue"]}
df = pd.DataFrame(data)

encoder.fit(df.Color)
labels = encoder.transform(df.Color)

In [ ]:
labels

In [ ]:
data = {"Name": ["홍길동", "이주연", "박지성", "손흥민", "안정환"]}
df = pd.DataFrame(data) 

encoder.fit(df.Name)
labels = encoder.transform(df.Name)

In [ ]:
df

In [ ]:
import numpy as np 
conditionList = [
  (df["Class"] == "A"),
  (df["Class"] == "B"),
  (df["Class"] == "C"),
  (df["Class"] == "D"),
  (df["Class"] == "E"),
  (df["Class"] == "F"),
]

choiceList = list(range(6))

np.select(condlist=conditionList, choicelist=choiceList)

In [ ]:
np.select(condlist=[(True,), (True,)], choicelist=[0, 1])

In [ ]:
df["Class"].map({"A":0, "B": 1, "C": 2, "D": 3, "E": 4, "F": 5})

In [ ]:
df["Class"].map({
  "A": 0, 
  "B": 1, 
  "C": 2, 
  "D": 3, 
  "E": 4, 
  "F": 5, 
})

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder 
obj = {"Class": ["A", "B", "A", "C", "E", "D", "D", "A", "F"]}
df = pd.DataFrame(obj)

encoder = LabelEncoder()
encoder.fit(df["Class"])
labels = encoder.transform(df["Class"])

In [ ]:
labels

In [ ]:
labels.shape

In [ ]:
labels2 = encoder.transform(df["Class"]).reshape(-1, 1)

In [ ]:
labels2.shape

In [ ]:
oh_encoder = OneHotEncoder(sparse_output=False)
oh_encoder.fit(labels2)
oh_labels = oh_encoder.transform(labels2)
oh_labels

In [ ]:
df["Class_B"] = np.where(df["Class"] == "B", 1, 0)

In [ ]:
df

In [ ]:
obj = {"Class": ["A", "B", "A", "C", "E", "D", "D", "A", "F"]}
df = pd.DataFrame(obj)

In [ ]:
df

In [ ]:
df.loc[0, "Class_B"] = 1
df["Class_B"].fillna(0).astype(int)


In [ ]:
df

In [ ]:
df.isnull()

In [ ]:
import pandas as pd
import numpy as np 
from sklearn.preprocessing import LabelEncoder, OneHotEncoder 

obj = {
  "student_id": ['s1', 's2', 's3', 's4', 's5', 's6'], 
  'score': [55, 90, 85, 71, 63, 99]
}

df = pd.DataFrame(obj)
display(df)

In [ ]:
df["grade"] = pd.cut(
  df["score"], 
  bins=[0, 60, 70, 80, 90, 100], 
labels=["가", "양", "미", "우", "수"]
)

In [ ]:
df

In [ ]:
pd.cut(
  df["score"], 
  bins=[0, 60, 70, 80, 90, 100], 
  labels=["가", "양", "미", "우", "수"]
)

In [ ]:
lb_encoder = LabelEncoder()
lb_encoder.fit(df["grade"])
lb_labels = lb_encoder.transform(df["grade"])
print(lb_labels)

In [ ]:
print(lb_encoder.classes_)

In [ ]:
lb_labels_2d = lb_labels.reshape(-1, 1)

In [ ]:
lb_labels_2d

In [ ]:
oh_encoder = OneHotEncoder(sparse_output=False)
oh_encoder.fit(lb_labels_2d)

In [ ]:
oh_labels = oh_encoder.transform(lb_labels_2d)

In [ ]:
oh_labels

In [86]:
from sklearn.preprocessing import LabelEncoder

obj = {
  "Class": ['A', 'B', 'A', 'C', 'E', 'D', 'D', 'A', 'F' ]
}

df = pd.DataFrame(obj)

encoder = LabelEncoder()
encoder.fit(df.Class)
labels = encoder.transform(df.Class)

print(labels)

[0 1 0 2 4 3 3 0 5]


In [87]:
conditionList = [
  (df["Class"] == 'A'), 
  (df["Class"] == 'B'), 
  (df["Class"] == 'C'), 
  (df["Class"] == 'D'), 
  (df["Class"] == 'E'), 
  (df["Class"] == 'F'), 
]

choiceList = list(range(6))

np.select(condlist=conditionList, choicelist=choiceList)

array([0, 1, 0, 2, 4, 3, 3, 0, 5])

In [88]:
df

Class
0     A
1     B
2     A
3     C
4     E
5     D
6     D
7     A
8     F

In [89]:
df["Class"].map(arg={
  "A": 0, 
  "B": 1, 
  "C": 2, 
  "D": 3, 
  "E": 4, 
  "F": 5
})

0    0
1    1
2    0
3    2
4    4
5    3
6    3
7    0
8    5
Name: Class, dtype: int64

In [92]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
obj = {
  "Class": ['A', 'B', 'A', 'C', 'E', 'D', 'D', 'A', 'F' ]
}

df = pd.DataFrame(obj)

encoder = LabelEncoder() 
encoder.fit(df["Class"])
labels = encoder.transform(df["Class"]).reshape(-1, 1)
print(labels)


oh_encoder = OneHotEncoder(sparse_output=False)
oh_encoder.fit(labels) 
oh_labels = oh_encoder.transform(labels)

print(oh_labels)

[[0]
 [1]
 [0]
 [2]
 [4]
 [3]
 [3]
 [0]
 [5]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [102]:
obj = {
  "Class": ['A', 'B', 'A', 'C', 'E', 'D', 'D', 'A', 'F' ]
}
df = pd.DataFrame(obj)

pd.get_dummies(df)
# print(result)

Class_A  Class_B  Class_C  Class_D  Class_E  Class_F
0     True    False    False    False    False    False
1    False     True    False    False    False    False
2     True    False    False    False    False    False
3    False    False     True    False    False    False
4    False    False    False    False     True    False
5    False    False    False     True    False    False
6    False    False    False     True    False    False
7     True    False    False    False    False    False
8    False    False    False    False    False     True

In [97]:
pd.get_dummies(df, drop_first=True) 

Class_B  Class_C  Class_D  Class_E  Class_F
0    False    False    False    False    False
1     True    False    False    False    False
2    False    False    False    False    False
3    False     True    False    False    False
4    False    False    False     True    False
5    False    False     True    False    False
6    False    False     True    False    False
7    False    False    False    False    False
8    False    False    False    False     True

In [105]:
import pandas as pd

# 예시 데이터
obj = {
    "Class": ['A', 'B', 'A', 'C', 'E', 'D', 'D', 'A', 'F']
}
df = pd.DataFrame(obj)

# get_dummies 사용
result = pd.get_dummies(df)

# 불리언 값이 있을 경우 1, 0으로 변환
result = result.astype(int)

print(result)

   Class_A  Class_B  Class_C  Class_D  Class_E  Class_F
0        1        0        0        0        0        0
1        0        1        0        0        0        0
2        1        0        0        0        0        0
3        0        0        1        0        0        0
4        0        0        0        0        1        0
5        0        0        0        1        0        0
6        0        0        0        1        0        0
7        1        0        0        0        0        0
8        0        0        0        0        0        1


In [107]:
df

Class
0     A
1     B
2     A
3     C
4     E
5     D
6     D
7     A
8     F

In [109]:
np.where(df["Class"] == "B", 1, 0)

array([0, 1, 0, 0, 0, 0, 0, 0, 0])

In [10]:
import pandas as pd
import numpy as np 
from sklearn.preprocessing import LabelEncoder, OneHotEncoder 

obj = {
  "student_id": ['s1', 's2', 's3', 's4', 's5', 's6'], 
  "score": [55, 90, 85, 71, 63, 99]
}
df = pd.DataFrame(obj)

df["grade"] = pd.cut(
  df["score"], 
  bins=[0, 60, 70, 80, 90, 100], 
  labels=["가", "양", "미", "우", "수"]
)

lb_encoder = LabelEncoder()
lb_encoder.fit(df["grade"])
lb_labels = lb_encoder.transform(df["grade"])

print(lb_labels)

lb_labels_2d = lb_labels.reshape(-1, 1)

oh_encoder = OneHotEncoder(sparse_output=False)
oh_encoder.fit(lb_labels_2d)
oh_labels = oh_encoder.transform(lb_labels_2d)
print(oh_labels)

[0 4 4 1 3 2]
[[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]]
