In [1]:
import numpy as np


In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])

In [3]:
arr_1d[0]

np.int64(1)

In [4]:
arr_1d[2]

np.int64(3)

In [8]:
arr = np.array([1.15, -2.33, 3.457, -4.095])
arr

array([ 1.15 , -2.33 ,  3.457, -4.095])

In [12]:
np.round(arr, decimals=0)

array([ 1., -2.,  3., -4.])

In [13]:
a = [3.14, 2.1111]
round(a)

TypeError: type list doesn't define __round__ method

In [15]:
a  = [[1, 2, 3], [4, 5, 6]]
a[0][1]
a[1, 2]

TypeError: list indices must be integers or slices, not tuple

In [16]:
arr_1d = np.arange(8) 

In [17]:
print(arr_1d)

[0 1 2 3 4 5 6 7]


In [19]:
a  =arr_1d.reshape(2, 4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [20]:
b = a.reshape(4, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [24]:
c = b.reshape(2, 2, 2)
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [25]:
a.reshape(-1, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [26]:
a.reshape(2, -1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [27]:
a.reshape(3, -1)

ValueError: cannot reshape array of size 8 into shape (3,newaxis)