In [2]:
from sklearn.metrics import confusion_matrix 

y_true = [0, 0, 0, 1, 1, 1]
y_pred =[ 0, 1, 0, 1, 1, 1]

confusion_matrix(y_true, y_pred)

y_true = ['A', 'A', 'A', 'B', 'B', 'B']
y_pred = ['A', 'B', 'A', 'B', 'B', 'B']

confusion_matrix(y_true, y_pred, labels=['A','B'])

array([[2, 1],
       [0, 3]])

In [3]:
y_true = [0, 0, 0, 1, 1, 2, 2, 2, 2]
y_pred = [0, 1, 1, 1, 0, 0, 1, 2, 2]

confusion_matrix(y_true, y_pred)

array([[1, 2, 0],
       [1, 1, 0],
       [1, 1, 2]])

In [7]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score 

y_true = [0, 0, 0, 1, 1, 1]
y_pred = [0, 1, 0, 1, 1, 1]


accuracy = accuracy_score(y_true, y_pred)
print(accuracy)

recall = recall_score(y_true, y_pred) 
print(recall)

precision = precision_score(y_true, y_pred) 
print(precision)

f1 = f1_score(y_true, y_pred) 
print(f1)

0.8333333333333334
1.0
0.75
0.8571428571428571


In [8]:
from sklearn.metrics import roc_curve, auc 

y_true = [0, 0, 0, 1, 1, 1]
y_score = [0.1, 0.75, 0.35, 0.92, 0.81, 0.68]

fpr, tpr, thresholds = roc_curve(y_true, y_score)

AUC = auc(fpr, tpr)
print(AUC)

0.888888888888889


In [12]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error 

import numpy as np 
np.random.seed(123)

y_true = np.random.random_sample(5)
print(y_true)

y_pred = np.random.random_sample(5)
print(y_pred)

mse = mean_squared_error(y_true, y_pred) 
print(mse)

mae = mean_absolute_error(y_true, y_pred) 
print(mae) 

mape = mean_absolute_percentage_error(y_true, y_pred) 
print(mape)

[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]
[0.42310646 0.9807642  0.68482974 0.4809319  0.39211752]
0.17581754220802784
0.36474003862364796
1.0843148337483364
